### ISSUE TITLE
Latest version incompatibility

### ISSUE THREAD

**Issue by xboct02** [Crendgrim/AutoHUD#138]
Conflict with the Exordium mod

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-12-08 02:37:10
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "mod.crend.autohud.component.state.ComponentState.updateNextTick()" because "mod.crend.autohud.component.Components.Health.state" is null
	at mod.crend.autohud.component.EventHandler.lambda$registerEvents$16(EventHandler.java:92)
	at mod.crend.libbamboo.event.ClientEventHandler$GameState.tick(ClientEventHandler.java:49)
	at mod.crend.libbamboo.event.ClientEventHandler.tick(ClientEventHandler.java:219)
	at mod.crend.libbamboo.fabric.LibBambooMod.lambda$onInitializeClient$0(LibBambooMod.java:12)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$cin001$fabric-lifecycle-events-v1$onEndTick(class_310.java:12185)
	at net.minecraft.class_310.method_1574(class_310.java:2012)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Crendgrim** [comment]
Thanks for the report, fixed in 8.1
