### ISSUE TITLE
Auto HUD  2.5+1.19.3: Game crashes when trying to mount saddled horses

### ISSUE THREAD

**Issue by rght925h** [Crendgrim/AutoHUD#32]
When trying to mount a saddled horse of any type, the game crashes with the error below:

`Unreported exception thrown!
java.lang.ClassCastException: class net.minecraft.class_4587 cannot be cast to class net.minecraft.class_1316 (net.minecraft.class_4587 and net.minecraft.class_1316 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a396c1e)
	at net.minecraft.class_329.mixinextras$bridge$726ca59e-1599-4430-b8ae-ddaf26900315$method_1752(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.wrapOperation$zeb000$autoHud$wrapMountJumpBar(class_329.java:2147) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:239) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:910) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]`

It is not possible to return to the game until unloading Auto HUD and dismounting the horse.
Hope this helps - **thank you** for making this wonderful mod! :-)

**Comment by Crendgrim** [comment]
Ah, what a silly little bug. Have pushed a fix, thank you for reporting!
