### ISSUE TITLE
DisguiseLib incompability - crash at startup

### ISSUE THREAD

**Issue by arquxx** [Crendgrim/AutoHUD#6]
Hi there
mod version 1.5.1
fabric 1.18.2
```

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 21.05.2022, 03:41
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'disguiselib'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at mod.crend.autohud.component.ScoreboardHelper.updateTeam(ScoreboardHelper.java:34)
	at net.minecraft.class_269.handler$zji000$updateScoreboardTeam(class_269.java:543)
	at net.minecraft.class_269.method_1154(class_269.java)
	at net.minecraft.class_268.method_1145(class_268.java:165)
	at xyz.nucleoid.disguiselib.impl.DisguiseLib.init(DisguiseLib.java:18)
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198)
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy45.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "mod.crend.autohud.config.Config.armor()" because "mod.crend.autohud.AutoHud.config" is null
	at mod.crend.autohud.component.Component.<clinit>(Component.java:14)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

```

**Comment by Crendgrim** [comment]
Should be fixed in ff93021585acc0fb69e8d338380fbe39dd9dab29 (released as 1.5.2) :)
