### ISSUE TITLE
[Bug]: Error upon loading Minecraft

### ISSUE THREAD

**Issue by Jouto55** [Crendgrim/AutoHUD#90]
When trying to start the game with AutoHUD (and Dynamic Crosshair), the game runs into errors

![image](https://github.com/Crendgrim/AutoHUD/assets/148708399/cb029389-df41-4577-b46d-8d8a053c1d74)

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-01-28 18:31:46
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.20-universal.jar%23321!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.2.20-universal.jar%23321!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.UtilMixin,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.2.20-universal.jar%23321!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:darkness.MixinGameRenderer,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:do_a_barrel_roll.mixins.json:client.roll.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:seamless_loading_screen-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	YetAnotherConfigLibExtensions (yaclx), Version: 1.10
		at TRANSFORMER/yaclx@1.10/mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:27)
Stacktrace:
	at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:27) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
-- MOD dynamiccrosshair --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: dev/isxander/yacl3/config/v2/api/ConfigClassHandler
		at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:27) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.yaclx.opt.ConfigStore.init(ConfigStore.java:147) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:87) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.dynamiccrosshair.config.ConfigHandler.<clinit>(ConfigHandler.java:11) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:mixin,re:classloading}
		at mod.crend.dynamiccrosshair.DynamicCrosshair.init(DynamicCrosshair.java:30) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:mixin,re:classloading}
		at mod.crend.dynamiccrosshair.forge.DynamicCrosshairForgeEvents.onClientSetup(DynamicCrosshairForgeEvents.java:25) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:classloading,pl:eventbus:A}
		at mod.crend.dynamiccrosshair.forge.__DynamicCrosshairForgeEvents_onClientSetup_FMLClientSetupEvent.invoke(.dynamic) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:classloading,pl:eventbus:B}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.20.jar%23318!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.20.jar%23317!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

	Mod File:dynamiccrosshair-7.4.4+1.20-forge.jar
	Failure message: Dynamic Crosshair (dynamiccrosshair) encountered an error during the sided_setup event phase
		java.lang.NoClassDefFoundError: dev/isxander/yacl3/config/v2/api/ConfigClassHandler
	Mod Version: 7.4.4+1.20
	Mod Issue URL: https://github.com/Crendgrim/DynamicCrosshair/issues
	Exception message: java.lang.ClassNotFoundException: dev.isxander.yacl3.config.v2.api.ConfigClassHandler
Stacktrace:
	at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:27) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.yaclx.opt.ConfigStore.init(ConfigStore.java:147) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:87) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.dynamiccrosshair.config.ConfigHandler.<clinit>(ConfigHandler.java:11) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:mixin,re:classloading}
	at mod.crend.dynamiccrosshair.DynamicCrosshair.init(DynamicCrosshair.java:30) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:mixin,re:classloading}
	at mod.crend.dynamiccrosshair.forge.DynamicCrosshairForgeEvents.onClientSetup(DynamicCrosshairForgeEvents.java:25) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:classloading,pl:eventbus:A}
	at mod.crend.dynamiccrosshair.forge.__DynamicCrosshairForgeEvents_onClientSetup_FMLClientSetupEvent.invoke(.dynamic) ~[dynamiccrosshair-7.4.4+1.20-forge.jar%23260!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.20.jar%23318!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.20.jar%23317!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

-- MOD autohud --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: dev/isxander/yacl3/config/v2/api/ConfigClassHandler
		at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:27) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.yaclx.opt.ConfigStore.init(ConfigStore.java:147) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:87) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:71) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
		at mod.crend.autohud.config.ConfigHandler.<clinit>(ConfigHandler.java:7) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:mixin,re:classloading}
		at mod.crend.autohud.AutoHud.init(AutoHud.java:26) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:mixin,re:classloading}
		at mod.crend.autohud.forge.AutoHudModEvents.onClientSetup(AutoHudModEvents.java:25) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:classloading,pl:eventbus:A}
		at mod.crend.autohud.forge.__AutoHudModEvents_onClientSetup_FMLClientSetupEvent.invoke(.dynamic) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:classloading,pl:eventbus:B}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.20.jar%23318!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.20.jar%23317!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

	Mod File: autohud-6.3.4+1.20.1-forge.jar
	Failure message: Auto HUD (autohud) encountered an error during the sided_setup event phase
		java.lang.NoClassDefFoundError: dev/isxander/yacl3/config/v2/api/ConfigClassHandler
	Mod Version: 6.3.4+1.20.1
	Mod Issue URL: https://github.com/Crendgrim/AutoHUD/issues
	Exception message: java.lang.ClassNotFoundException: dev.isxander.yacl3.config.v2.api.ConfigClassHandler
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at mod.crend.yaclx.opt.WithYacl.<init>(WithYacl.java:27) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.yaclx.opt.ConfigStore.init(ConfigStore.java:147) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:87) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.yaclx.opt.ConfigStore.<init>(ConfigStore.java:71) ~[yaclx-1.12+1.20.2-forge.jar%23352!/:?] {re:classloading}
	at mod.crend.autohud.config.ConfigHandler.<clinit>(ConfigHandler.java:7) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:mixin,re:classloading}
	at mod.crend.autohud.AutoHud.init(AutoHud.java:26) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:mixin,re:classloading}
	at mod.crend.autohud.forge.AutoHudModEvents.onClientSetup(AutoHudModEvents.java:25) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:classloading,pl:eventbus:A}
	at mod.crend.autohud.forge.__AutoHudModEvents_onClientSetup_FMLClientSetupEvent.invoke(.dynamic) ~[autohud-6.3.4+1.20.1-forge.jar%23241!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.20.jar%23318!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.20.jar%23317!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

Mods:
  [✔] AI-Improvements-1.20-0.5.2
  [✔] AmbientSounds_FORGE_v5.3.8_mc1.20.1
  [✔] Amplified_Nether_1.20.4_v1.2.4
  [✔] athena-forge-1.20.1-3.1.1
  [✔] auto_third_person-forge-1.20.1-2.1
  [✔] autohud-6.3.4+1.20.1-forge
  [✔] backpacked-forge-1.20.1-2.2.5
  [✔] bendy-lib-forge-4.0.0
  [✔] bestylewither-forge-mc1.20-1.6.0
  [✔] BetterAdvancements-1.20.1-0.3.2.162
  [✔] betterchunkloading-1.20.1-3.0
  [✔] bettercombat-forge-1.8.4+1.20.1
  [✔] BetterThirdPerson-Forge-1.20-1.9.0
  [✔] bygonenether-1.3.2-1.20.x
  [✔] canary-mc1.20.1-0.3.2
  [✔] chunksending-1.20.1-2.8
  [✔] clientcrafting-1.20.1-1.7
  [✔] cloth-config-11.1.118-forge
  [✔] Clumps-forge-1.20.1-12.0.0.3
  [✔] connectivity-1.20.1-4.9
  [✔] CreativeCore_FORGE_v2.11.23_mc1.20.1
  [✔] CullLessLeaves-Reforged-1.20.1-1.0.5
  [✔] cupboard-1.20.1-2.2
  [✔] do_a_barrel_roll-forge-3.5.0+1.20.1
  [✔] dynamiccrosshair-7.4.4+1.20-forge
  [✔] embeddium-0.2.18+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.3-build
  [✔] entityculling-forge-1.6.2-mc1.20.1
  [✔] experimentalsettingsdisabler-1.20.1-3.0
  [✔] extrasounds-1.1-1.20.1-forge
  [✔] FallingTree-1.20.1-4.3.4
  [✔] farsight-1.20.1-3.6
  [✔] fastasyncworldsave-1.20.1-1.4
  [✔] ferritecore-6.0.1-forge
  [✔] FiltPick-forge-mc1.20.1-0.0.2
  [✔] firstperson-forge-2.3.2-mc1.20.1
  [✔] framework-forge-1.20.1-0.6.16
  [✔] getittogetherdrops-forge-1.20-1.3
  [✔] gpumemleakfix-1.20.1-1.8
  [✔] inventorysorter-1.20.1-23.0.1
  [✔] KryptonReforged-0.2.3
  [✔] letmedespawn-forge-1.20.x-1.2.0
  [✔] Log-Begone-Forge-1.20.1-1.0.8
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] modelfix-1.14
  [✔] modernfix-forge-5.12.1+mc1.20.1
  [✔] MouseTweaks-forge-mc1.20-2.25
  [✔] notenoughanimations-forge-1.7.0-mc1.20.1
  [✔] Nullscape_1.20.4_v1.2.4
  [✔] oculus-mc1.20.1-1.6.13
  [✔] player-animation-lib-forge-1.0.2-rc1+1.20
  [✔] PresenceFootsteps-1.20.1-1.9.1-beta.1
  [✔] recipeessentials-1.20.1-3.2
  [✔] redirector-1.20.1-4.4.0-forge
  [✔] riverredux-0.3.1
  [✔] seamless-loading-screen-2.0.3+1.20.1-forge
  [✔] skinlayers3d-forge-1.6.2-mc1.20.1
  [✔] smoothchunk-1.20.1-3.5
  [✔] structureessentials-1.20.1-3.2
  [✔] takesapillage-1.0.3-1.20.1
  [✔] tectonic-mod-1.19.3-v2.2
  [✔] TerraBlender-forge-1.20.1-3.0.1.2
  [✔] Terralith_1.20.4_v2.4.11
  [✔] textrues_embeddium_options-0.1.3+mc1.20.1
  [✔] tia-1.20-1.1-forge
  [✔] TravelersTitles-1.20-Forge-4.0.1
  [✔] tru.e-ending-v1.1.0b
  [✔] veinmining-forge-1.3.0+1.20.1
  [✔] visuality-forge-2.0.2
  [✔] XaerosWorldMap_1.37.7_Forge_1.20
  [✔] YungsApi-1.20-Forge-4.0.2
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterDungeons-1.20-Forge-4.0.3
  [✔] YungsBetterEndIsland-1.20-Forge-2.0.5
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.4
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4
  [✔] YungsBetterStrongholds-1.20-Forge-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Forge-3.0.3

Modloader: Forge 47.2.20
MC Version: 1.20.1
OS: Windows 11

**Comment by Crendgrim** [comment]
This is such a frustrating bug. YACL (YetAnotherConfigLib) updated the way it can be used, and I'm using the newer version of its API. But the newer version then never worked properly on Forge 1.20.1 in particular, and *still* hasn't been fixed (see YetAnotherConfigLib#124 ). It's fine for my mods if YACL is not present at all, but in your case it looks like some mod (badly) bundles the old version of YACL?
Bah, I'll have to hard code it to ignore YACL on 1.20.1. I really expected that to not be necessary :(

**Comment by Crendgrim** [comment]
Multiple issues are at play here.

YACL 3 changed the way the API is used. YACL 3 never worked on 1.20.1 Forge. A fix has been merged, and I just poked isXander to make a release; that should hopefully fix this.

It would have been fine to use my mods without any YACL installed, but some mod in your list appears to be bundling the older version of YACL inside of it.

**Comment by Jouto55** [comment]
> Multiple issues are at play here.
> 
> 
> 
> YACL 3.2 changed the way the API is used. YACL 3.2 never worked on 1.20.1 Forge. A fix has been merged, and I just poked isXander to make a release; that should hopefully fix this.
> 
> 
> 
> It would have been fine to use my mods without any YACL installed, but some mod in your list appears to be bundling the older version of YACL inside of it.

It appears that it's Seamless Loading Screen that caused the error, as YACL is embedded to it.

![image](https://github.com/Crendgrim/AutoHUD/assets/148708399/dec41697-d1b7-4ed7-8128-0873365bf5e7)

**Comment by Crendgrim** [comment]
YACL *finally* updated to include the fix. Update YACL and everything should finally work again.
